### ISSUE TITLE
How to run , could provide the read me

### ISSUE THREAD

**Issue by skanel** [Kein1945/GPS_Teltonika_Server#2]
How to run, could provide the read me, please.

Thanks

**Comment by Kein1945** [comment]
Oh! It was so long time ago!
As you can read at readme:

> There is two parts. Snifr.py - script that receive connections from trackers, parse data, and write it to redis-db db_daemon.py - script that waiting new data from redis, and send it to database.

So you need to run both scripts. Python2 required. But if you are using another database you can replace db_daemon.py with your own script, that retrieve data from redis and send it to another database.
Redis was chosen because sometimes I had to much data and our database was very slow to make some much inserts with separate requests.
